// Generated by scripts/emit_dts.py for session-lattice (reads HTTP server).
// Regenerate with `coily exec emit-dts` (auto via pre-commit). Do not edit by hand.

export interface SessionLatticeReads {
  /** Healthz */
  "GET /healthz"(): Promise<Record<string, string>>;

  /** List Views */
  "GET /views"(): Promise<Record<string, Record<string, unknown>[]>>;
}
