// Generated by scripts/emit_dts.py - do not edit by hand.
// HTTP server: session-lattice (reads)
// Regenerate with: `coily exec emit-dts`
// (runs automatically on every commit via pre-commit).

export interface SessionLatticeReads {
  /**
   * Healthz
   */
  "GET /healthz"(): Promise<Record<string, string>>;

  /**
   * List Views
   */
  "GET /views"(): Promise<Record<string, Record<string, unknown>[]>>;
}
