class SessionLattice < Formula
  include Language::Python::Virtualenv

  desc "Materialized-view service over Claude session data (embedded DuckDB)"
  homepage "https://github.com/coilysiren/session-lattice"
  # url/tag/revision are rewritten by the release pipeline at every tag push.
  # The pipeline dispatches to coilysiren/homebrew-tap, which runs
  # bump-session-lattice.yml to rewrite this block via the Contents API
  # (web-flow signed, satisfying the signed-commits ruleset).
  url "ssh://git@github.com/coilysiren/session-lattice.git", tag: "v0.0.0", revision: "0000000000000000000000000000000000000000"
  license "MIT"
  head "https://github.com/coilysiren/session-lattice.git", branch: "main"

  depends_on "python@3.13"

  # Python resource blocks for transitive deps are generated by
  # `coily exec brew-resources` (homebrew-pypi-poet against the
  # synced uv venv). The release workflow regenerates them and
  # commits them alongside the version bump.
  #
  # Initial bring-up - run `coily exec brew-resources >> Formula/session-lattice.rb`
  # after `coily exec sync`, then move the printed blocks into the
  # marker below.
  #
  # BEGIN RESOURCES (managed by coily exec brew-resources)
  # END RESOURCES

  def install
    virtualenv_install_with_resources
  end

  service do
    run [opt_bin/"session-lattice", "serve"]
    keep_alive true
    working_dir "#{Dir.home}/.session-lattice"
    log_path var/"log/session-lattice.log"
    error_log_path var/"log/session-lattice.err.log"
    environment_variables(
      SESSION_LATTICE_HOME: "#{Dir.home}/.session-lattice",
      SESSION_LATTICE_HOST: "127.0.0.1",
      SESSION_LATTICE_PORT: "7778",
      SESSION_LATTICE_REPO_RECALL_URL: "http://127.0.0.1:7777",
      SESSION_LATTICE_REFRESH_INTERVAL_SECONDS: "60",
      PATH: "#{HOMEBREW_PREFIX}/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin",
    )
  end

  def caveats
    <<~EOS
      To configure session-lattice (port, repo-recall URL, refresh interval, etc.):
        brew services edit session-lattice
        brew services restart session-lattice
      Edits to the service file persist across `brew upgrade`.

      The DuckDB database file lives at ~/.session-lattice/session-lattice.duckdb.
      Attach the DuckDB UI read-only against the live file:
        duckdb -readonly ~/.session-lattice/session-lattice.duckdb -ui
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/session-lattice --version")
    assert_match "session-lattice", shell_output("#{bin}/session-lattice --help")
  end
end
