#!/usr/bin/env -S uv run --script
"""Emit session-lattice.d.ts from the FastAPI reads app's OpenAPI schema.

Stable output: routes sorted by path then method, no absolute paths, no
per-machine timestamps. Diffs only when the actual surface changes. Used as a
pre-commit hook so the checked-in spec never drifts from the server.

Why a custom emitter instead of a generic openapi-to-ts tool:
* Output stays under our voice rules (header style, comment shape).
* No node toolchain pulled into a Python repo just for a spec dump.
* Tool sorting and ref handling stay deterministic across machines.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from session_lattice.config import Config  # noqa: E402
from session_lattice.service import create_reads_app  # noqa: E402

SPEC_PATH = REPO_ROOT / "session-lattice.d.ts"
HEADER = """\
// Generated by scripts/emit_dts.py for session-lattice (reads HTTP server).
// Regenerate with `coily exec emit-dts` (auto via pre-commit). Do not edit by hand.

export interface SessionLatticeReads {
"""
FOOTER = "}\n"


def _probe_config() -> Config:
    # FastAPI route registration only needs a Config object. The reads handlers
    # touch DuckDB lazily on request; openapi() does not invoke them.
    return Config(
        db_path=Path("/tmp/session-lattice-emit.duckdb"),
        host="127.0.0.1",
        port=0,
        repo_recall_url="http://127.0.0.1:7777",
        refresh_interval_seconds=60.0,
    )


def _resolve_ref(schema: dict[str, Any], components: dict[str, Any]) -> dict[str, Any]:
    ref = schema.get("$ref")
    if not isinstance(ref, str) or not ref.startswith("#/components/schemas/"):
        return schema
    name = ref.rsplit("/", 1)[-1]
    return components.get("schemas", {}).get(name, {})


def ts_type_for(schema: dict[str, Any], components: dict[str, Any]) -> str:
    """Map a JSON Schema fragment to a TypeScript type expression.

    Narrow on purpose. session-lattice routes today return shallow JSON;
    extend here when a route grows a richer response shape.
    """
    if "$ref" in schema:
        schema = _resolve_ref(schema, components)
    any_of = schema.get("anyOf") or schema.get("oneOf")
    if isinstance(any_of, list) and any_of:
        return " | ".join(ts_type_for(s, components) for s in any_of)
    enum = schema.get("enum")
    if isinstance(enum, list) and enum:
        return " | ".join(f'"{v}"' if isinstance(v, str) else str(v) for v in enum)
    t = schema.get("type")
    if isinstance(t, list):
        return " | ".join(ts_type_for({"type": tt}, components) for tt in t)
    if t == "string":
        return "string"
    if t in ("number", "integer"):
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "null":
        return "null"
    if t == "array":
        return f"{ts_type_for(schema.get('items', {}), components)}[]"
    if t == "object" or "properties" in schema or "additionalProperties" in schema:
        props = schema.get("properties") or {}
        if props:
            required = set(schema.get("required") or [])
            fields = []
            for name in sorted(props):
                ts = ts_type_for(props[name], components)
                marker = "" if name in required else "?"
                fields.append(f"{name}{marker}: {ts}")
            return "{ " + "; ".join(fields) + " }"
        ap = schema.get("additionalProperties")
        if isinstance(ap, dict):
            return f"Record<string, {ts_type_for(ap, components)}>"
        if ap is True or ap is None:
            return "Record<string, unknown>"
        return "Record<string, never>"
    return "unknown"


def _response_schema(op: dict[str, Any]) -> dict[str, Any]:
    responses = op.get("responses") or {}
    for code in ("200", "default"):
        body = responses.get(code)
        if not isinstance(body, dict):
            continue
        content = body.get("content") or {}
        json_body = content.get("application/json") or {}
        schema = json_body.get("schema")
        if isinstance(schema, dict):
            return schema
    return {}


def _description(op: dict[str, Any]) -> str:
    desc = op.get("description") or op.get("summary") or ""
    return str(desc).strip()


def render_route(
    method: str, path: str, op: dict[str, Any], components: dict[str, Any]
) -> str:
    """Render one HTTP route as a TSDoc-commented method signature."""
    schema = _response_schema(op)
    response_ts = ts_type_for(schema, components) if schema else "unknown"

    lines: list[str] = []
    desc = _description(op).replace("\n", " ").strip()
    if desc:
        lines.append(f"  /** {desc} */")
    key = f'"{method.upper()} {path}"'
    lines.append(f"  {key}(): Promise<{response_ts}>;")
    return "\n".join(lines)


def render_spec(openapi: dict[str, Any]) -> str:
    components = openapi.get("components") or {}
    paths = openapi.get("paths") or {}
    entries: list[tuple[str, str, dict[str, Any]]] = []
    for path in sorted(paths):
        methods = paths[path] or {}
        for method in sorted(methods):
            if method.lower() not in {"get", "post", "put", "patch", "delete"}:
                continue
            op = methods[method]
            if not isinstance(op, dict):
                continue
            entries.append((method, path, op))
    blocks = [render_route(m, p, op, components) for m, p, op in entries]
    body = "\n\n".join(blocks)
    return HEADER + body + "\n" + FOOTER


def main() -> int:
    app = create_reads_app(_probe_config())
    spec = render_spec(app.openapi())
    existing = SPEC_PATH.read_text() if SPEC_PATH.exists() else ""
    if spec == existing:
        return 0
    SPEC_PATH.write_text(spec)
    print(
        f"emit_dts: wrote {SPEC_PATH.name} ({len(spec.splitlines())} lines)",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
